name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Use Node.js Version 22
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        
    - name: Install Dependency
      run: npm ci
    
    - name: Start Aplication
      run: npm start &
      
    - name: Run Test
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: Deploy Student register
          uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.RENDER_SERVICE_ID }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            wait_deploy: true 
